client_cert: /root/.disney/test-user.crt
client_key: /root/.disney/test-user.key
ca_cert: /root/.disney/disneyland.crt
connect_to: 192.168.65.1:50051
db_uri: postgres://192.168.65.1/disneyland?sslmode=disable
